### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by GustavoSHan** [SequoiaDB/SequoiaDB#109]
高可用+高性能的设置是不是createRG()时，数据节点创建2个组？
我是3台机，宕机任意一台，可读可写需要在什么地方做配置吗？
还是巨杉可以自动响应切换？

**Comment by SequoiaDBOfficial** [comment]
我们来举个栗子：
假如你部署成这个样子
|机器1     |机器2     |机器3     |
|coord     |coord     |coord     |
|cata      |cata      |cata      |
|dataRG1   |dataRG1   |dataRG1   |
|dataRG2   |          |          |

1、如果你建表的时候指定Group为dataRG2，那在表上写数据，只需要在机器1上写，同时，如果机器1宕机了，表上无论是读或写都是不可以的；
2、如果你建表的时候指定Group为dataRG1，那表上写数据，会自动分到所有机器，任意机器宕机，会自动切换到另一台机器读/写。
3、如果在dataRG1上建表，可以指定ReplSize，默认值为1，意思是只在任意一台机器写成功就返回。这个设置下，写入性能比较高，但是如果写入同时宕机，数据就会丢失，因为其它机器可能还没有同步。如果倾向于安全多于速度，ReplSize就要设得更大。
建表参数见：http://doc.sequoiadb.com/cn/SequoiaDB-cat_id-1432190821-edition_id-300

**Comment by SequoiaDBOfficial** [comment]
如果你要比较性能和可用性折中的方案，那弄几个多副本的数据组，但是表ReplSize=1，也是可以考虑的。
