### ISSUE TITLE
在服务器异常掉电的情况下， 如何保证数据完整性？

### ISSUE THREAD

**Issue by GordonLinnn** [SequoiaDB/SequoiaDB#113]
在服务器异常掉电的情况下，会导致哪些影响？对哪些数据有影响？如何保证该情况下的数据完整性？

**Comment by SequoiaDBOfficial** [comment]
1.如果掉电的机器是一个datagroup的主节点所在的机器，那么对于涉及到这个datagroup的任何变更操作都会临时中断，直到这个datagroup重新选出主节点才恢复写操作，当然如果在掉电前已经写入到该节点上的数据没有及时同步到其它备节点上，那么这部分是会丢失的。读操作的话不受影响。
2.如果掉电的机器是一个datagroup的备节点所在的机器，除非由于该节点的异常退出，导致该节点所在的datagroup无法选主，从而导致原来的主节点降备，不然的话，对于涉及该datagroup的读写操作都不受影响。
3.掉电后机器恢复正常后，该机器上的节点都会进入到异常退出修复状态，data节点会进入全量同步状态，与主节点进行全量同步，这个过程的时间长短会因数据量的大小而变化。

解决方法如下：
软件上：将重要的数据节点分别部署到不同的机器上，并且在对数据做任何变更操作时（写，修改，删除），至少要在2节点上完成写操作后才返回，再做下一步操作
硬件上：为服务器安装ups备用电源，防止服务器的异常掉电情况发生。
