### ISSUE TITLE
SequoaiDB 现在有与spring和spring-data集成的计划吗?

### ISSUE THREAD

**Issue by FridaRobert** [SequoiaDB/SequoiaDB#114]
SequoaiDB 现在有与spring和spring-data集成的计划吗？
比如在spring内置 SequoaiDB db连接的bean，简单声明后就可以直接调用。 以及通过spring-data把常用的CRUD方法都封装好。

**Comment by SequoiaDBOfficial** [comment]
暂时还没有看到太多这方面的需求。
你有兴趣的话可以开一个项目，一起完善哦。
