### ISSUE TITLE
ossVer.c:92:20: error: 'SDB_ENGINE_BUILD_TIME' was not declared in this scope

### ISSUE THREAD

**Issue by berli** [SequoiaDB/SequoiaDB#14]
scons: Building targets ...
g++ -o build/linux2/normal/shell/engine/oss/ossVer.o -c -Wnon-virtual-dtor -fPIC -fno-strict-aliasing -ggdb -pthread -Wno-write-strings -Wall -Wsign-compare -Wno-unknown-pragmas -Winvalid-pch -Wno-address -pipe -fno-builtin-memcmp -O3 -D__STDC_LIMIT_MACROS -DHAVE_CONFIG_H -DSDB_DLL_BUILD -D_GNU_SOURCE -DXP_UNIX -D_FILE_OFFSET_BITS=64 -DSDB_CLIENT -DSDB_SHELL -DSDB_SSL -ISequoiaDB/engine/include -ISequoiaDB/engine/client -Ithirdparty/crypto/openssl-1.0.1c/include -ISequoiaDB/engine/gtest/include -ISequoiaDB/engine/pcre -Ithirdparty/boost -ISequoiaDB/engine/ssh2 -Ijava/jdk_linux64/include -Ijava/jdk_linux64/include/linux -Ithirdparty/parser/sm/js/lib/release/linux64/include SequoiaDB/engine/oss/ossVer.cpp
In file included from SequoiaDB/engine/oss/ossVer.cpp:38:0:
SequoiaDB/engine/oss/ossVer.c: In function 'void ossGetVersion(INT32*, INT32*, INT32*, INT32*, const CHAR**)':
SequoiaDB/engine/oss/ossVer.c:62:18: error: 'SDB_ENGINE_BUILD_TIME' was not declared in this scope
       *ppBuild = SDB_ENGINE_BUILD_TIME ;
                  ^
SequoiaDB/engine/oss/ossVer.c: In function 'void ossSprintVersion(const CHAR*, CHAR*, UINT32, BOOLEAN)':
SequoiaDB/engine/oss/ossVer.c:82:33: error: 'SDB_ENGINE_BUILD_TIME' was not declared in this scope
                    OSS_NEWLINE, SDB_ENGINE_BUILD_TIME,
                                 ^
SequoiaDB/engine/oss/ossVer.c:92:20: error: 'SDB_ENGINE_BUILD_TIME' was not declared in this scope
                    SDB_ENGINE_BUILD_TIME ) ;
                    ^
scons: *** [build/linux2/normal/shell/engine/oss/ossVer.o] Error 1
scons: building terminated because of errors.

**Comment by wangzhonnew** [comment]
resolved
