### ISSUE TITLE
Error code problem

### ISSUE THREAD

**Issue by WesleyLeo** [SequoiaDB/SequoiaDB#20]
Hello there, I am a newbie of this.
When I tried to use this database, I got an error code: 
-222: RouteID is different from the local
How to solve?
When an error code appears, where can I tell what this error code stands for?
Is there a document about this?

**Comment by SequoiaDBOfficial** [comment]
1.The -222 error indicates that the node is not registered successfully. It is recommended to check whether the host name and its corresponding host ip are configured in the /etc/hosts file.
2.It is recommended to ping the hostname to check if the machine's hostname matches the hostname configured in the /etc/hosts file.
3.Try restarting the node/host and operating again.
For questions about the error code, you can check it out here：http://www.sequoiadb.com/en/index.php?m=Files&a=index&cat_id=143&edition_id=0#
