### ISSUE TITLE
What commands can I check the structure of SDB cluster?

### ISSUE THREAD

**Issue by PatrickCruz122** [SequoiaDB/SequoiaDB#29]
What commands can I check the structure of SDB cluster?

**Comment by SequoiaDBOfficial** [comment]
These commands will help you quickly understand the structure of the sdb cluster:
View all sdb nodes on the current host:
  ` sdblist -t all`
View all data, catalog, and coordination nodes on the current host:
  `sdblist -l`
View the status of all domains in the current cluster:
   `db.listDomains();`
View all replication groups in the current cluster:
  ` db.listReplicaGroups();`
List all collection spaces:
   `db.listCollectionSpaces();`
List all collections:
    `db.listCollections();`
