### ISSUE TITLE
Sequoiadb是否有备份文件的校验功能

### ISSUE THREAD

**Issue by OliverFinn** [SequoiaDB/SequoiaDB#30]
用 db.backupOffline() 方法进行了全量备份，如何确保备份文件是否可用？
万一文件损坏了的话，即使恢复也是有问题的。
是否有类似oracle的validate这种校验机制？

**Comment by SequoiaDBOfficial** [comment]
db.backupOffline() 备份生成的文件本身没有提供校验工具，用户可通过计算 md5 值的方式简单校验文件是否有被损坏。
计算 md5 值的方法，linux 如：
`md5sum <备份文件名>`
