### ISSUE TITLE
安装Python驱动时报错

### ISSUE THREAD

**Issue by MaxwellMartin** [SequoiaDB/SequoiaDB#32]
编译github上的Python驱动，在安装时报cannot find extendsion：sdb
![image](https://user-images.githubusercontent.com/42232690/44022638-c346f124-9f1a-11e8-9009-b4164b15a903.png)

**Comment by SequoiaDBOfficial** [comment]
1、安装报错的原因可能是因为编译器启用了C++11的特性，可以尝试使用4.8版本以下的gcc编译器，或者关闭C++11特性进行编译。
2、可以使用官网上编译完成的Python驱动：[http://download.sequoiadb.com/cn/index-cat_id-2]()
