### ISSUE TITLE
备份时如何指定备份到某一台机器

### ISSUE THREAD

**Issue by WesleyLeo** [SequoiaDB/SequoiaDB#35]
备份时如何指定备份到某一台机器？现有a、b、c3台，连到b的协调节点进行backupoffline全备，为什么备份到c那台机去了？

**Comment by SequoiaDBOfficial** [comment]
1、连接coord节点进行全量备份，则该数据组的数据会备份到组的主节点所在机器上。当时主节点在c机器上，因此备份数据也在那。
2、如果需要备份到指定主机，只能通过直连该主机数据节点进行备份，但只能备份当前节点的数据，适用于备份少数节点。如果需要全量备份，则需要分别直连所有节点分别备份，此时如此操作会比较麻烦。
方法：
```
> var dbdata = new Sdb( 'hostname1', 'servicename1' `);
> dbdata.backupOffline( { Name: 'backupName', Description: 'backup data node' } );
```
3、建议：直连coord节点全量备份，恢复时将备份文件分别拷贝到对应主机。
参考资料：
官网数据备份介绍： http://doc.sequoiadb.com/cn/SequoiaDB-cat_id-1432190664-edition_id-208
