### ISSUE TITLE
SequoiaDB shell中如何表示is not null

### ISSUE THREAD

**Issue by PatrickCruz122** [SequoiaDB/SequoiaDB#37]
SequoiaDB shell 中is not null怎么表示?

**Comment by SequoiaDBOfficial** [comment]
在Sequoiadb shell中is not null可用$isnull表示，比如
`{ “key”: { $isnull: 0 } }`
,返回字段key存在且不为null的记录
参考资料
官网$isnull介绍：http://doc.sequoiadb.com/cn/SequoiaDB-cat_id-1432190909-edition_id-208
