### ISSUE TITLE
想问一下这个oid如何拿到？

### ISSUE THREAD

**Issue by FridaRobert** [SequoiaDB/SequoiaDB#38]
![qq 20180823145648](https://user-images.githubusercontent.com/42177073/44509622-cf91e700-a6e4-11e8-9127-4a2645059878.png)

**Comment by FridaRobert** [comment]
![qq 20180823152827](https://user-images.githubusercontent.com/42177073/44511157-34e7d700-a6e9-11e8-99f3-152740d2f994.png)
得到的结果是这样的
难道是我的remove写法有问题？

**Comment by SequoiaDBOfficial** [comment]
打印一下personCursor.oid
可以先用find查询一下是否符合，再用remove
remove没条件筛选就是删全部的记录
![qq 20180823153513](https://user-images.githubusercontent.com/13619839/44511439-26e68600-a6ea-11e8-847a-50f697cf7fd2.png)

**Comment by FridaRobert** [comment]
结果是这样的

![qq 20180823153641](https://user-images.githubusercontent.com/42177073/44511526-7927a700-a6ea-11e8-8243-40121a5d8464.png)
![qq 20180823153756](https://user-images.githubusercontent.com/42177073/44511578-98263900-a6ea-11e8-9840-9cb6e16d668b.png)
![qq 20180823153759](https://user-images.githubusercontent.com/42177073/44511579-99effc80-a6ea-11e8-8f19-d95739e50efd.png)
![qq 20180823153807](https://user-images.githubusercontent.com/42177073/44511582-9b212980-a6ea-11e8-9d6b-ba00a72783e7.png)

**Comment by SequoiaDBOfficial** [comment]
不要打印出来看，打印了就取了一次了，游标里面就没记录了
查询出来的是游标，要先用next()获取一条记录
参考文档：http://doc.sequoiadb.com/cn/SequoiaDB-cat_id-1432190852-edition_id-112

**Comment by FridaRobert** [comment]
搞定了搞定了，多谢
![qq 20180823154408](https://user-images.githubusercontent.com/42177073/44511875-6497de80-a6eb-11e8-9350-1181392ce82a.png)
