### ISSUE TITLE
SQL查询优化

### ISSUE THREAD

**Issue by OliverFinn** [SequoiaDB/SequoiaDB#42]
请问我一个SQL语句查询用了十秒，数据量两亿，还有优化的空间吗？
` "select sum(amount) as amount from accountdetail where validate_state = '1' and bus_code='20160711315040002' ";`
没创建索引之前查询用时10分钟左右

**Comment by OliverFinn** [comment]
![qq 20180827162526](https://user-images.githubusercontent.com/42062600/44649227-dd61a800-aa15-11e8-833b-6a89fb0ebfd4.png)

![qq 20180827162534](https://user-images.githubusercontent.com/42062600/44649234-e0f52f00-aa15-11e8-8e62-f9eed6e8461c.png)

**Comment by SequoiaDBOfficial** [comment]
可以试试运行这个语句，`explain (ANALYZE, VERBOSE) + 你的 SQL 语句`，看看执行情况。
很大可能是因为目前 sum 不能下压到 postgres 运行造成的。

**Comment by OliverFinn** [comment]
嗯 改成`select * from table where code="" `后提升到3秒就查询出来了
如果想用sum 可以给个建议 能够很快查询出来的吗？

**Comment by SequoiaDBOfficial** [comment]
目前暂时不具备下压sum的能力，所以速度似乎只能这样。
内置sql的sum不存在这个问题。
