### ISSUE TITLE
SequoiaDB的日志级别能调整么？

### ISSUE THREAD

**Issue by DebbieMadisonS** [SequoiaDB/SequoiaDB#46]
感觉后面实际运行比较需要的log信息有slowQuery这种的，节点间heartbeat失败的，这样的信息会有么？

**Comment by SequoiaDBOfficial** [comment]
可以用diaglevel参数来调整
 `--diaglevel -v num`

1.指定诊断日志打印级别。SequoiaDB中诊断日志从0-5分别代表：SEVERE, ERROR, EVENT, WARNING, INFO, DEBUG。
2.如果不指定，则默认为WARNING。默认是WARNING级别，会打印WARNING或更严重的信息
3.可以单独设定不同节点的log级别
