### ISSUE TITLE
在同一台主机上，可以装两个不同版本的sdb么?

### ISSUE THREAD

**Issue by AustinAngusE** [SequoiaDB/SequoiaDB#47]

**Comment by SequoiaDBOfficial** [comment]
可以但是不建议.
正常情况下应该没啥问题，测试环境可以，生产环境还是建议每台机器走独立的实例，避免硬件资源争用
如果是测试学习，其实一个安装，创建多个实例就可以了，没必要每个实例对应一个安装。
但是想要使用OM自动安装和管理的话，一个机器上只能管理一个版本的集群。
如果要另外安装一个，只能用全手动的方式安装和管理。
