### ISSUE TITLE
执行SQL语句报语法错误

### ISSUE THREAD

**Issue by AustinAngusE** [SequoiaDB/SequoiaDB#48]
v2.6中，执行db.exec('select * from foo.bar where a is not null') 报语法错误，该如何解决？

**Comment by SequoiaDBOfficial** [comment]
1、v2.6尚不支持 is not null 的内置SQL，建议使用NoSQL中的操作符 $isnull 代替
<http://doc.sequoiadb.com/cn/SequoiaDB-cat_id-1432190909-edition_id-0>；
2、注意：v2.8.4之前版本写作 isnot null；v2.8.4之后版本写作 is not null；
