### ISSUE TITLE
OM备份恢复

### ISSUE THREAD

**Issue by VictorBorgF** [SequoiaDB/SequoiaDB#49]
当OM失效时，选择整个重装还是备份恢复?

**Comment by SequoiaDBOfficial** [comment]
1、OM作为监控管理节点，本身不参与业务，所以就算是OM节点故障也不会对业务产生影响。但是，我们也正在尝试将OM节点做到高可用，不过现在这个版本(v2.6)还没有完善。
2、如果用户担心OM因单点故障而导致无法恢复，用户可以对OM的数据文件及配置文件进行备份。
3、用户可在如下情况发生之后，手工对OM的数据文件进行备份：
a) 使用OM创建、删除集群。
b) 使用OM添加、删除机器。
c) 使用OM添加、删除业务。
等等；OM也类似一个数据节点，它也有相关的数据表。原则上每次进行写表操作(如上介绍的三种情况)之后，都应该对OM的数据文件进行备份。但是在实际操作过程，用户可以酌情敲定备份的时机。
4、用户对OM进行备份之前，应该先停止OM（bin/sdbstart -t om）。
5、从OM备份中恢复的步骤如下：
a) 先关闭OM。（bin/sdbstop -t om）
b) 将OM数据目录下的所有内容删掉。
（OM目录默认路径为：<数据库安装目录>/database/sms/<OMServiceName>）
c) 将已备份的OM目录内容拷贝回来。
（先删除OM所在的目录，再把已备份的OM目录恢复）
d) 若配置文件有改动，应该恢复备份时的配置文件的内容。
（ OM配置文件默认路径为：<数据库安装目录>/conf/local/<OMServiceName>/sdb.conf）
e) 重启OM。（bin/sdbstart -t om）
