### ISSUE TITLE
巨杉数据库压缩问题

### ISSUE THREAD

**Issue by PatrickCruz122** [SequoiaDB/SequoiaDB#51]
将集合的Compressed设置为true后，巨杉数据库会在什么时候压缩数据，是我每插入一条数据，会单单压缩这一条，还是说，会汇总多条数据，然后压缩，或者是其他什么时机？我查看当前的压缩比，看起来基本就没有压缩

**Comment by SequoiaDBOfficial** [comment]
集合的压缩有2种，snappy和lzw，snappy是每条记录压缩，lzw是根据数据一定规模后进行采样，并生成字典，然后对后续的数据进行压缩。
