### ISSUE TITLE
Compile error at omCommand.cpp:3765

### ISSUE THREAD

**Issue by blakdis** [SequoiaDB/SequoiaDB#54]
**Describe the bug**
Compile error at SequoiaDB/engine/omsvc/omCommand.cpp:3765

**To Reproduce**
1. git clone https://github.com/SequoiaDB/SequoiaDB.git
2. scons --engine
3. see error blow:
SequoiaDB/engine/omsvc/omCommand.cpp:3765:2: error: #endif without #if
 #endif
  ^
SequoiaDB/engine/omsvc/omCommand.cpp:9875:2: error: #endif without #if
 #endif
  ^
SequoiaDB/engine/omsvc/omCommand.cpp:10669:2: error: #endif without #if
 #endif // SDB_ENTERPRISE

**Comment by wangzhonnew** [comment]
looks like some mistake in the script to remove code between SDB_ENTERPRISE macro before uploading to github. Now fixed

![image](https://user-images.githubusercontent.com/5110272/45142230-911f2080-b1ea-11e8-94cf-191034d5401c.png)
![image](https://user-images.githubusercontent.com/5110272/45142313-ce83ae00-b1ea-11e8-8462-5ca9e50b0c5d.png)
