### ISSUE TITLE
关于 SequoiaDB云数据库 的连接问题

### ISSUE THREAD

**Issue by AustinAngusE** [SequoiaDB/SequoiaDB#58]
1、请问，在java端，怎么访问 云端数据库（http://cloud.sequoiadb.com）的？我看到有 实例名和连接地址。
2、我想咨询一下共享数据库和个人数据库除了有效时间外，还有什么区别？

**Comment by SequoiaDBOfficial** [comment]
一：
访问云数据和访问本地数据库是一样的，只是云数据库使用的是域名，而后者使用的是主机名。可以参考一下这里：
http://doc.sequoiadb.com/cn/Sequ ... 190739-edition_id-0

二：
共享数据库是大家共用的，没有时间的限制，但是，你写的数据可能会被别人修改。
个人数据库是私有的，但是有效期只有一个星期。
