### ISSUE TITLE
请问SequoiaDB数据类型和SequoiaDB--postgresql数据类型的对应关系从哪可以查到啊？

### ISSUE THREAD

**Issue by AlanNewelll** [SequoiaDB/SequoiaDB#72]

**Comment by SequoiaDBOfficial** [comment]
可以在这里看看
http://doc.sequoiadb.com/cn/SequoiaDB-cat_id-1432190715-edition_id-300

![qq 20180918164636](https://user-images.githubusercontent.com/13619839/45675673-6f1a8c00-bb62-11e8-84ef-3dc835b6dfe2.png)
