### ISSUE TITLE
数据重构期间，其他的节点是否可以提供正常服务?

### ISSUE THREAD

**Issue by GustavoHann** [SequoiaDB/SequoiaDB#83]

**Comment by SequoiaDBOfficial** [comment]
全量同步期间其它节点可以正常服务：
![qq 20180929093557](https://user-images.githubusercontent.com/13619839/46239428-21f0b280-c3cb-11e8-9c83-9d538b2fc68e.png)
http://tutorial.sequoiadb.com/cn/Detail-id-2

**Comment by SequoiaDBOfficial** [comment]
![qq 20180929093708](https://user-images.githubusercontent.com/13619839/46239532-3b462e80-c3cc-11e8-9ccc-744daf3d6a7d.png)
http://doc.sequoiadb.com/cn/index-cat_id-1432190652-edition_id-300
