### ISSUE TITLE
这个错误咋解决

### ISSUE THREAD

**Issue by Nathan06Li** [SequoiaDB/SequoiaDB#95]
```
mysql> use cs;
Database changed
mysql> create table cl(a int, b int, c text, primary key(a, b) ) engine = SequoiaDB ;
ERROR 1030 (HY000): Got error 49841 from storage engine
```

我的SequoiaDB  是standalone模式的
http://doc.sequoiadb.com/cn/SequoiaDB-cat_id-1521595283-edition_id-0   
按文档教程的操作步骤一步步下来的

**Comment by SequoiaDBOfficial** [comment]
错误码减去50000是SDB的错误码
`SDB_RTN_COORD_ONLY	-159	该操作仅适用于协调节点`
可以看一下输出配置
`mysql> show variables like 'sequoiadb%';`

**Comment by Nathan06Li** [comment]
![qq 20181025161308](https://user-images.githubusercontent.com/42143746/47485570-eed9fb80-d870-11e8-9a0b-d4de4c9ceb84.png)
![qq 20181025161316](https://user-images.githubusercontent.com/42143746/47485588-f699a000-d870-11e8-8867-83cabc02c7fc.png)
是这样的

**Comment by SequoiaDBOfficial** [comment]
将配置参数“sequoiadb_use_partition”设置为“OFF”禁止创建默认分区表试试

**Comment by Nathan06Li** [comment]
的确是这个问题，现在可以了

**Comment by SequoiaDBOfficial** [comment]
standalone有很多功能性局限
建议搭个最简单的集群
